### ISSUE TITLE
Source bundler version from gemfile.lock

### ISSUE THREAD

**Issue by paulasaurus** [engineyard/engineyard-serverside#184]
Presently we install a custom version of bundler if the customer specifies one in the Gemfile itself. With the arrival of Bundler 2 we are seeing issues wherein the customer bundles with Bundler 2 locally, so `BUNDLED WITH BUNDLER 2.0.1` is set in the gemfile.lock file, but the don't add it to the Gemfile, so serverside still uses 1.7.9. This can lead to compatibility issues.

Can we look to install the version specified in the lock file, so that we use automatically the same Bundler version they are using locally?

This would also help with some of the issues seen by customers where upgrading to high 1.x versions also resolves issues.

**Comment by ess** [comment]
This is an excellent suggestion that is probably nowhere near as straight-forward as it sounds. That doesn't mean that we shouldn't do it, but more that it's probably going to raise some surprises and require *RATHER* rigorous testing.

Assigned to @remotedevops for implementation. Please holler if you run into issues.

**Comment by ess** [comment]
Thinking about this a bit more, here's what I'd suggest for determining the `bundler` version to use:

* Attempt to grab it from `Gemfile.lock`
* Failing that, attempt to grab it from `Gemfile`
* Failing that, system default

Basically, just tack an extra check at the beginning of the current `bundler` resolution method, so all of the bases are covered.

**Comment by remotedevops** [comment]
It turns out we already have this feature on 2.6.17. https://github.com/engineyard/engineyard-serverside/commit/cefc9fd4bc032e96b83f8213d47d63c556df4c31

**Comment by ess** [comment]
@paulasaurus Can you verify the above?

**Comment by paulasaurus** [comment]
Tested:

* No bundler in the Gemfile
* `BUNDLED WITH 1.10.6` in the Gemfile.lock file

```
+    00s  Initializing engineyard-serverside 2.6.17.
....
+    02s     $ ssh -i /home/deploy/.ssh/internal -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/ey-ss-known-hosts20190529-26236-154ou0t -o PasswordAuthentication=no -o ServerAliveInterval=60 deploy@ec2-54-236-250-90.compute-1.amazonaws.com 'sudo sh -l -c '\''export GIT_SSH="/data/bundertesting/shared/config/bundertesting-ssh-wrapper" && export LANG="en_US.UTF-8" && unset RUBYOPT BUNDLE_PATH BUNDLE_FROZEN BUNDLE_WITHOUT BUNDLE_BIN BUNDLE_GEMFILE && gem list bundler | grep "bundler " | egrep -q "1\.10\.6[,)]" || gem install bundler -q --no-rdoc --no-ri -v "1.10.6"'\'
+    03s       Successfully installed bundler-1.10.6
```

```
ip-172-20-4-165 ~ # gem list bundler

*** LOCAL GEMS ***

bundler (1.10.6)
```

* Re-bundled locally with 1.17.3
* `BUNDLED WITH 1.17.3` in the Gemfile.lock file

```
01s     $ ssh -i /home/deploy/.ssh/internal -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/ey-ss-known-hosts20190529-745-ql2cxg -o PasswordAuthentication=no -o ServerAliveInterval=60 deploy@ec2-54-236-250-90.compute-1.amazonaws.com 'sudo sh -l -c '\''export GIT_SSH="/data/bundertesting/shared/config/bundertesting-ssh-wrapper" && export LANG="en_US.UTF-8" && unset RUBYOPT BUNDLE_PATH BUNDLE_FROZEN BUNDLE_WITHOUT BUNDLE_BIN BUNDLE_GEMFILE && gem list bundler | grep "bundler " | egrep -q "1\.17\.3[,)]" || gem install bundler -q --no-rdoc --no-ri -v "1.17.3"'\'
+    02s       Successfully installed bundler-1.17.3
```

```
ip-172-20-4-165 ~ # gem list bundler

*** LOCAL GEMS ***

bundler (1.17.3, 1.10.6)
```

https://cloud.engineyard.com/app_deployments/112035/environment

**Comment by paulasaurus** [comment]
* Removed `BUNDLED WITH` from the Gemfile.lock file

```
ssh -i /home/deploy/.ssh/internal -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/ey-ss-known-hosts20190529-5926-hsh126 -o PasswordAuthentication=no -o ServerAliveInterval=60 deploy@ec2-54-236-250-90.compute-1.amazonaws.com 'sudo sh -l -c '\''export GIT_SSH="/data/bundertesting/shared/config/bundertesting-ssh-wrapper" && export LANG="en_US.UTF-8" && unset RUBYOPT BUNDLE_PATH BUNDLE_FROZEN BUNDLE_WITHOUT BUNDLE_BIN BUNDLE_GEMFILE && gem list bundler | grep "bundler " | egrep -q "1\.14\.6[,)]" || gem install bundler -q --no-rdoc --no-ri -v "1.14.6"'\'
+    01s       Successfully installed bundler-1.14.6
+    01s       1 gem installed
```

```
ip-172-20-4-165 ~ # gem list bundler

*** LOCAL GEMS ***

bundler (1.14.6)
```

**Comment by paulasaurus** [comment]
* Bundled with 2.0.1 locally

```
 01s     $ ssh -i /home/deploy/.ssh/internal -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/ey-ss-known-hosts20190529-11520-3i17sj -o PasswordAuthentication=no -o ServerAliveInterval=60 deploy@ec2-54-236-250-90.compute-1.amazonaws.com 'sudo sh -l -c '\''export GIT_SSH="/data/bundertesting/shared/config/bundertesting-ssh-wrapper" && export LANG="en_US.UTF-8" && unset RUBYOPT BUNDLE_PATH BUNDLE_FROZEN BUNDLE_WITHOUT BUNDLE_BIN BUNDLE_GEMFILE && gem list bundler | grep "bundler " | egrep -q "2\.0\.1[,)]" || gem install bundler -q --no-rdoc --no-ri -v "2.0.1"'\'
+    02s       ERROR:  Error installing bundler:
+    02s       	bundler requires Ruby version >= 2.3.0.
```

So picked up the version fine, but install failed.

**Comment by ess** [comment]
> So picked up the version fine, but install failed.

That sounds like "not so much a serverside problem." :grin: 

With verification in place, shall we close this up?

**Comment by paulasaurus** [comment]
Ha, yeah, sorry that was never meant to pin the failure on serverside 😄 

I will close this now.
